#!/bin/bash
zcat ../stacks_b2/KOD03_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_051.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_052.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_053.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_054.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_055.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_056.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_057.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_058.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_059.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_060.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_061.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_062.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_063.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_064.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_065.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_066.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_067.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_068.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_069.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_070.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_071.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_072.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_073.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_074.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_075.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_076.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_077.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_078.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_079.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_080.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_081.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_082.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_083.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_084.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_085.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_086.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_087.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_088.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_089.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_090.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_091.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_092.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_093.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_094.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_095.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_096.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/KOD03_097.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/AD06_048.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/WC05_048.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/HS04_048.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PI04_048.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_048.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PS12_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/GS13_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_063.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_075.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_079.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_094.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_095.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_096.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_097.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_131.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/PWS12_133.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_001.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_009.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_017.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_025.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_033.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_041.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_002.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_010.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_018.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_026.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_034.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_042.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_003.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_011.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_019.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_027.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_035.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_043.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_004.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_012.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_020.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_028.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_036.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_044.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_005.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_013.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_021.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_029.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_037.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_045.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_006.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_014.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_022.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_030.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_038.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_046.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_007.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_015.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_023.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_031.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_039.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_047.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_008.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_016.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_024.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_032.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_040.tags.tsv.gz| python countloci_single_tagsfile.py
zcat ../stacks_b2/UP03_048.tags.tsv.gz| python countloci_single_tagsfile.py
